language: c++
compiler:
  - gcc
install:
  - echo yes | sudo add-apt-repository ppa:nmi/llvm-3.3
  - sudo apt-get update -qq
  - sudo apt-get install -qq llvm-3.3-dev
  - sudo apt-get install -qq flex bison libreadline-dev
script: make
